language: node_js
os:
  - linux
node_js:
  - "6"
sudo: enabled
cache:
 directories:
    - node_modules
branches:
  only:
    - dev
    
script:
  - npm run coverage
  
after_success:
  - npm run report-coverage

