language: node_js
os:
  - linux
  - osx
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
sudo: false
cache:
 directories:
    - node_modules
branches:
  only:
    - dev
    
script:
  - npm run coverage
  
after_success:
  - npm run report-coverage

